# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e469574336c1c77df7475b480e450ff6b628b8fcfa7c785354d8a1028e0ba87ada06645460a9c8153ce7c37f3f2d84d31bdf37385c896f2e64c34eb3ad09262f

test:
  secret_key_base: 0dc8587fc1757952e10c196d4d0765b11f397a36725ce24f6e9b83791c1c9d88aac9aa1fe6c14624f3fc8387bb5976e9fbbf7fa3caabae5e7e47ed40465add43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
